import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Provider from "@/app/Provider";

const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Almanet',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    );
}
